\documentclass[final]{beamer}
\usepackage{grffile}
\mode<presentation>{\usetheme{CambridgeUSPOL}}

\usepackage[utf8]{inputenc}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{natbib}
\usepackage{graphicx}
\usepackage{array,booktabs,tabularx}
\newcolumntype{Z}{>{\centering\arraybackslash}X}

% rysunki
\usepackage{tikz}
\usepackage{ifthen}
\usepackage{xxcolor}
\usetikzlibrary{arrows}
\usetikzlibrary[topaths]
\usetikzlibrary{decorations.pathreplacing}
%\usepackage{times}\usefonttheme{professionalfonts}  % times is obsolete
\usefonttheme[onlymath]{serif}
\boldmath
\usepackage[orientation=portrait,size=a0,scale=1.4,debug]{beamerposter}                       % e.g. for DIN-A0 poster
%\usepackage[orientation=portrait,size=a1,scale=1.4,grid,debug]{beamerposter}                  % e.g. for DIN-A1 poster, with optional grid and debug output
%\usepackage[size=custom,width=200,height=120,scale=2,debug]{beamerposter}                     % e.g. for custom size poster
%\usepackage[orientation=portrait,size=a0,scale=1.0,printer=rwth-glossy-uv.df]{beamerposter}   % e.g. for DIN-A0 poster with rwth-glossy-uv printer check
% ...
%

\usecolortheme{seagull}
\useinnertheme{rectangles}
\setbeamercolor{item projected}{bg=darkred}
% \setbeamertemplate{enumerate items}[default]
\setbeamertemplate{navigation symbols}{}
\setbeamercovered{transparent}
\setbeamercolor{block title}{fg=darkred}
\setbeamercolor{local structure}{fg=darkred}

\setbeamercolor*{enumerate item}{fg=darkred}
\setbeamercolor*{enumerate subitem}{fg=darkred}
\setbeamercolor*{enumerate subsubitem}{fg=darkred}

\setbeamercolor*{itemize item}{fg=darkred}
\setbeamercolor*{itemize subitem}{fg=darkred}
\setbeamercolor*{itemize subsubitem}{fg=darkred}

\newlength{\columnheight}
\setlength{\columnheight}{92cm}
\renewcommand{\thetable}{}
\def\andname{,}
\authornote{}

\renewcommand{\APACrefatitle}[2]{}
\renewcommand{\bibliographytypesize}{\footnotesize} 
\renewcommand{\APACrefYearMonthDay}[3]{%
{\BBOP}{#1}
{\BBCP}
}

\begin{document}



<<knitrIntro, echo = FALSE, message=FALSE>>=
library(xtable)
library(ggplot2)
library(reshape2)

poster_theme <- theme(plot.background=element_rect(fill = "transparent",
                                                   colour = "transparent"),
                      axis.text.x = element_text(size=16), 
                      axis.text.y = element_text(size=16),
                      axis.title.x = element_text(size=19, vjust = -1), 
                      axis.title.y = element_text(size=19, vjust = 1),
                      legend.text = element_text(size=16), 
                      legend.title = element_text(size=19),
                      plot.title = element_text(size=27),
                      panel.background = element_rect(fill = "transparent",colour = "black"),
                      legend.direction="horizontal", legend.position = "bottom",
                      legend.background = element_rect(fill="NA"))
@


\date{}
\author{Micha\l{}  Burdukiewicz\inst{1}, Piotr Sobczyk\inst{2}, Pawe\l{} Mackiewicz\inst{1}, Stefan R{\"o}diger\inst{3}}

\institute{\textsuperscript{1}University of Wroc\l{}?aw, Department of Genomics, Poland 

\vspace{0.5cm}

\textsuperscript{2}Wroc\l{}aw University of Technology, Institute of Mathematics and Computer Science, Poland

\vspace{0.5cm}

\textsuperscript{3}Faculty of Natural Sciences, Brandenburg University of Technology 
Cottbus--Senftenberg, Germany}
}
\title{\huge Methods of Comparing Digital PCR Experiments}

\begin{frame}
\begin{columns}
\begin{column}{.44\textwidth}
\begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
\begin{minipage}[T]{.95\textwidth}
\parbox[t][\columnheight]{\textwidth}
{
\begin{block}{Introduction}
The outcome of digital PCR (dPCR) experiments are mean copies per partition ($\lambda$). Results are derived from the measured data, an ordered (in one or two dimensions) sequence of positive partitions. The usual analysis involves assumption the template molecules are Poisson distributed among partitions. On this premise, already proposed approaches, based on the confidence intervals~\citep{dube_mathematical_2008} or uncertainty quantification~\citep{bhat_single_2009}, allow a comparison of experiments. 
\end{block}
\vfill

\begin{block}{GLM testing framework}
Generalized Linear Models (GLM) are linear models for data, where the response variables may have non-normal distributions (as binomially distributed positive partitions in digital PCR experiments). We propose a model reflecting relationships in results of digital PCR as given by:
\begin{equation}
\log{Y} = \beta^T X
\end{equation}
where $Y$ are counts, $X$ are experiments names (categorical data) and $\beta$ are linear model coefficients for every experiment. Moreover, $\exp{\beta} = \lambda$.   
Estimated means copies per partitions obtained from the model are compared each other using multiple t-test~\citep{bretz_2010}.
The linear model above can be used only when the concentration of template molecules in samples is small (positive partitions contain very rarely more than 1 template particle). Higher concentrations basically requires binomial regression.

\end{block}
\vfill


\begin{block}{Multiple testing (MT) framework}
The dPCR experimentes are compared pairwise using the uniformly most powerful (UMP) ratio test~\citep{fay_2010}. Furthermore, computed p-values are adjusted using Benjamini & Hochberg correction~\citep{benjamini_1995} to control family-wise error rate.

The UMP ratio test has following null-hypothesis:
\begin{equation}
H_0: \frac{\lambda_1}{\lambda_2} = 1
\end{equation}


The Wilson's confidence intervals~\citep{brown_2001} are calculated independently for every dPCR experiment. The Dunn~--~\v{S}id\'{a}k correction ensures control of the family-wise error rate, because:

\begin{equation}
\prod_{i = 1}^{T} P(\theta_{i_L} < \theta_{i} < \theta_{i_U}) = 1 - \alpha
\end{equation}


\end{block}
\vfill


\begin{block}{Model evaluation}
Two approaches above were compared in a simulation approach.

<<dube_bat, echo = FALSE, message=FALSE,fig.width=12,fig.height=11.3>>=
load("ints_plot.RData")

ggplot(data=indat,aes(x= experiment,y = lambda,col = name))+
  geom_errorbar(aes(ymin=low,ymax=up),size=2) +
  geom_point(shape=16, size = 6, position = position_dodge(w = 0.6, h = 0)) + 
  geom_point(aes(y=real/765), shape=17, size = 6, colour = "black", alpha = 0.25) +
  scale_x_discrete("Experiment name") + 
  scale_y_continuous(expression(lambda)) + 
  scale_color_discrete("Method name:") + 
  poster_theme
@
\end{block}
\vfill



}
\end{minipage}
\end{beamercolorbox}
\end{column}


%new column ------------------------------------------------------    

\begin{column}{.53\textwidth}
\begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
\begin{minipage}[T]{.95\textwidth}  
\parbox[t][\columnheight]{\textwidth}
{


\begin{block}{Evaluation}
stuff stuff stuff
\end{block}
\vfill    

\begin{block}{Probability coverage of confidence intervals}

  Covarage probability is the proportion of the time that the interval contains the true value of $\lambda$.
  
  In the example below, we simulated 1000 droplet dPCR experiments and assed probability coverage of CI obtained by three methods: Dube's~\citep{dube_mathematical_2008}, Bhat's~\citep{bhat_single_2009} and by MT for each level of $\lambda$.
  
<<coverage, echo = FALSE, message=FALSE,fig.width=14.7,fig.height=10>>=
load("coverage.RData")

m_coverage <- m_coverage[m_coverage[["method"]] != "Non-adjusted", ]
m_coverage[["method"]] <- droplevels(m_coverage[["method"]])
m_coverage[["method"]] <- factor(m_coverage[["method"]],
                                 levels(m_coverage[["method"]])[c(1,3,2)])
ggplot(m_coverage, aes(x = prop, y = coverage, fill = method)) +
  geom_bar(stat="identity", position = "dodge") +
  scale_y_continuous("Probability coverage") + 
  scale_x_discrete(expression(lambda)) +
  scale_fill_discrete("Confidence intervals:") + 
  geom_hline(y = 0.95, colour = "black", size = 2, linetype = 5) +
  poster_theme
  @

The dashed black line marks 0.95 border.

<<coverage_table, echo = FALSE, message=FALSE,results='asis'>>=
dat <- as.data.frame(aggregate(coverage ~ method, m_coverage, mean))
colnames(dat)<- c("Method name", "Probability coverage")
print(xtable(dat, align = c("c", "c", "|", "c")), include.rownames = FALSE)
  @

On average, Dube's confidence intervals 
  
  \end{block}
  \vfill
  
  
  \begin{block}{Summary}
  
  \end{block}
  \vfill 
  
  \begin{block}{Avaibility}
  \footnotesize{
  dpcR web server: 
  
  %       \url{http://michbur.shinyapps.io/signalhsmm/}$\begin{array}{l}
  %         \begin{figure}[ht]
  %         \centering
  %         \scalebox{0.3}{
  %           \includegraphics{qrsignalhsmm.png}
  %         }
  %         \end{figure}
  %       \end{array}
  %       $
  
  dpcR R package: 
  
  \url{http://cran.r-project.org/web/packages/dpcR/}
  }
  \end{block}
  \vfill 

\begin{block}{Simulations}
We performed all in-silico experiments using the accurete digital PCR data simulations~\citep{jacobs_2014}.
\end{block}
\vfill
  
  \begin{block}{Bibliography}
  \tiny{
  \bibliographystyle{apalike}
  \bibliography{dpcrcits}
  }
  \end{block}
  \vfill
}
\end{minipage}
\end{beamercolorbox}
\end{column}
\end{columns}  
\end{frame}
\end{document}