\documentclass[final]{beamer}
\usepackage{grffile}
\mode<presentation>{\usetheme{CambridgeUSPOL}}

\usepackage[utf8]{inputenc}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{natbib}
\usepackage{graphicx}
\usepackage{array,booktabs,tabularx}
\newcolumntype{Z}{>{\centering\arraybackslash}X}

% rysunki
\usepackage{tikz}
\usepackage{ifthen}
\usepackage{xxcolor}
\usetikzlibrary{arrows}
\usetikzlibrary[topaths]
\usetikzlibrary{decorations.pathreplacing}
%\usepackage{times}\usefonttheme{professionalfonts}  % times is obsolete
\usefonttheme[onlymath]{serif}
\boldmath
\usepackage[orientation=portrait,size=a0,scale=1.4,debug]{beamerposter}                       % e.g. for DIN-A0 poster
%\usepackage[orientation=portrait,size=a1,scale=1.4,grid,debug]{beamerposter}                  % e.g. for DIN-A1 poster, with optional grid and debug output
%\usepackage[size=custom,width=200,height=120,scale=2,debug]{beamerposter}                     % e.g. for custom size poster
%\usepackage[orientation=portrait,size=a0,scale=1.0,printer=rwth-glossy-uv.df]{beamerposter}   % e.g. for DIN-A0 poster with rwth-glossy-uv printer check
% ...
%

\usecolortheme{seagull}
\useinnertheme{rectangles}
\setbeamercolor{item projected}{bg=darkred}
% \setbeamertemplate{enumerate items}[default]
\setbeamertemplate{navigation symbols}{}
\setbeamercovered{transparent}
\setbeamercolor{block title}{fg=darkred}
\setbeamercolor{local structure}{fg=darkred}

\setbeamercolor*{enumerate item}{fg=darkred}
\setbeamercolor*{enumerate subitem}{fg=darkred}
\setbeamercolor*{enumerate subsubitem}{fg=darkred}

\setbeamercolor*{itemize item}{fg=darkred}
\setbeamercolor*{itemize subitem}{fg=darkred}
\setbeamercolor*{itemize subsubitem}{fg=darkred}

\newlength{\columnheight}
\setlength{\columnheight}{92cm}
\renewcommand{\thetable}{}
\def\andname{,}
\authornote{}

\renewcommand{\APACrefatitle}[2]{}
\renewcommand{\bibliographytypesize}{\footnotesize} 
\renewcommand{\APACrefYearMonthDay}[3]{%
  {\BBOP}{#1}
  {\BBCP}
}

\begin{document}



<<knitrIntro, echo = FALSE, message=FALSE>>=
library(xtable)
library(ggplot2)
library(reshape2)
@


\date{}
\author{Micha\l{}‚  Burdukiewicz\inst{1}, Piotr Sobczyk\inst{2}, Pawe\l{}‚ Mackiewicz\inst{1}, Stefan R{\"o}diger\inst{3}}

\institute{\textsuperscript{1}University of Wroc\l{}‚aw, Department of Genomics, Poland 

\vspace{0.5cm}

\textsuperscript{2}Wroc\l{}‚aw University of Technology, Institute of Mathematics and Computer Science, Poland

\vspace{0.5cm}

\textsuperscript{3}Faculty of Natural Sciences, Brandenburg University of Technology 
Cottbus--Senftenberg, Germany}
}
\title{\huge Methods of Comparing Digital PCR Experiments}

\begin{frame}
  \begin{columns}
    \begin{column}{.44\textwidth}
      \begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
        \begin{minipage}[T]{.95\textwidth}
          \parbox[t][\columnheight]{\textwidth}
            {
    \begin{block}{Introduction}
The outcome of digital PCR (dPCR) experiments are mean copies per partition ($\lambda$). Results are derived from the measured data, an ordered (in one or two dimensions) sequence of positive partitions. The usual analysis involves assumption the template molecules are Poisson distributed among partitions. On this premise, already proposed approaches, based on the confidence intervals~\citep{dube_mathematical_2008} or uncertainty quantification~\citep{bhat_single_2009}, allow a comparison of experiments. 
    \end{block}
    \vfill
    
    \begin{block}{Multiple testing scheme}
    The dPCR experimentes are compared pairwise using the uniformly most powerful (UMP) ratio test~\citep{fay_2010}. Furthermore, computed p-values are adjusted using Benjamini & Hochberg correction~\citep{benjamini_1995} to control family-wise error rate.
    
    The UMP ratio test has following null-hypothesis:
    \begin{equation}
    H_0: \frac{\lambda_1}{\lambda_2} = 1
    \end{equation}
    
    
    The Wilson's confidence intervals~\citep{brown_2001} are calculated independently for every dPCR experiment. The Dunn -– \v{S}id\'{a}k correction ensures control of the family-wise error rate.
    \end{block}
    \vfill
   
    
    \begin{block}{Possible models}
<<echo = FALSE,message=FALSE,results='asis'>>=
plot(1L:5)
@ 
    \end{block}
    \vfill
    

    
            }
        \end{minipage}
      \end{beamercolorbox}
    \end{column}
    
    
%new column ------------------------------------------------------    
    
    \begin{column}{.53\textwidth}
      \begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
        \begin{minipage}[T]{.95\textwidth}  
          \parbox[t][\columnheight]{\textwidth}
            {
            
       
    \begin{block}{Evaluation}
    stuff stuff stuff
    \end{block}
    \vfill    
    
        
    
     
    \begin{block}{Summary}

    \end{block}
    \vfill 
    
        \begin{block}{Avaibility}
        \footnotesize{
      dpcR web server: 
      
%       \url{http://michbur.shinyapps.io/signalhsmm/}$\begin{array}{l}
%         \begin{figure}[ht]
%         \centering
%         \scalebox{0.3}{
%           \includegraphics{qrsignalhsmm.png}
%         }
%         \end{figure}
%       \end{array}
%       $
      
      dpcR R package: 
      
      \url{http://cran.r-project.org/web/packages/dpcR/}
        }
    \end{block}
    \vfill 
     
     
    \begin{block}{Bibliography}
      \bibliographystyle{apalike}
      \bibliography{dpcrcits}
    \end{block}
    \vfill
            }
        \end{minipage}
      \end{beamercolorbox}
    \end{column}
  \end{columns}  
\end{frame}
\end{document}